######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 14:16:42 2012
######################################################################

TEMPLATE = app
TARGET = TestMaybe 
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += Either.h Maybe.h TestMaybe.h
SOURCES += TestMaybe.cpp
